apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-boot-hpa
  namespace: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-boot-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
