version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=dev
      - SPRING_PROFILES_ACTIVE=${ENV}
    ports:
      - "8086:8080"  
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"  
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginxdockerfile
    ports:
      - "80:80"  
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
